### ISSUE TITLE
WM_CLOSE

### ISSUE THREAD

**Issue by etajima** [alexsilva/supervisor#26]
Is there any plan to support to send WM_CLOSE to close window application? 
I have tried some code to do this.
Is anybody interested in it?

**Comment by alexsilva** [comment]
Using the pywin32 api is it looks if possible.
[RadialController](https://github.com/microsoft/Windows-classic-samples/blob/1d363ff4bd17d8e20415b92e2ee989d615cc0d91/Samples/RadialController/cpp/RadialController.cpp#L81)

I have no plan to add this because usually the supervisor manages processes that do not use windows, only terminal.

I accept your contribution to add this new functionality through a pull request.
